# Generated by Django 3.1.7 on 2021-04-15 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('Admin', '0002_auto_20210414_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='institution_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.institution'),
        ),
        migrations.AddField(
            model_name='course',
            name='institution_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.institution'),
        ),
        migrations.AddField(
            model_name='fees',
            name='institution_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.institution'),
        ),
        migrations.AddField(
            model_name='score',
            name='institution_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.institution'),
        ),
        migrations.AddField(
            model_name='semester',
            name='institution_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.institution'),
        ),
    ]
