# Generated by Django 3.1.7 on 2021-04-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20210414_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='roles',
            new_name='name',
        ),
    ]
